#!/bin/bash
#SBATCH --job-name=DEG_plot
#SBATCH -p standard
#SBATCH -A mblurton_lab
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --error=slurm-%J.err
#SBATCH --mem 64G
#SBATCH --time=4:00:00

source ~/.bashrc
conda activate cicero

name="celltype_Nurr2c_vs_GFP"
infile="/dfs3b/swaruplab/smorabit/collab/woodlab/cocaine_mouse_2021/Nurr2c_vs_GFP/DEGs/data/celltype_Nurr2c_vs_GFP.csv"
outdir="/dfs3b/swaruplab/smorabit/collab/woodlab/cocaine_mouse_2021/Nurr2c_vs_GFP/DEGs/figures/"$name
mkdir $outdir

# setup other variables for plotting script
seurat="/dfs3b/swaruplab/smorabit/collab/woodlab/cocaine_mouse_2021/Nurr2c_vs_GFP/data/harmony_annotated.rds"
cluster="cell_type"
nlabel_volcano=10
volcano_color1="darkgoldenrod3"
volcano_color2="hotpink3"
ngenes_enrichr=100
nterms=20

# launch R script:
Rscript --vanilla /dfs3b/swaruplab/smorabit/collab/woodlab/cocaine_mouse_2021/Nurr2c_vs_GFP/bin/parallel_DEG_plotting.R \
  --infile $infile \
  --outdir $outdir \
  --name $name \
  --seurat $seurat \
  --cluster $cluster \
  --nlabel-volcano $nlabel_volcano \
  --volcano-color1 $volcano_color1 \
  --volcano-color2 $volcano_color2 \
  --ngenes-enrichr $ngenes_enrichr \
  --nterms-enrichr $nterms




name="cluster_Nurr2c_vs_GFP"
infile="/dfs3b/swaruplab/smorabit/collab/woodlab/cocaine_mouse_2021/Nurr2c_vs_GFP/DEGs/data/cluster_Nurr2c_vs_GFP.csv"
outdir="/dfs3b/swaruplab/smorabit/collab/woodlab/cocaine_mouse_2021/Nurr2c_vs_GFP/DEGs/figures/"$name
mkdir $outdir

# setup other variables for plotting script
seurat="/dfs3b/swaruplab/smorabit/collab/woodlab/cocaine_mouse_2021/Nurr2c_vs_GFP/data/harmony_annotated.rds"
cluster="annotation"
nlabel_volcano=10
volcano_color1="darkgoldenrod3"
volcano_color2="hotpink3"
ngenes_enrichr=100
nterms=20

# launch R script:
Rscript --vanilla /dfs3b/swaruplab/smorabit/collab/woodlab/cocaine_mouse_2021/Nurr2c_vs_GFP/bin/parallel_DEG_plotting.R \
  --infile $infile \
  --outdir $outdir \
  --name $name \
  --seurat $seurat \
  --cluster $cluster \
  --nlabel-volcano $nlabel_volcano \
  --volcano-color1 $volcano_color1 \
  --volcano-color2 $volcano_color2 \
  --ngenes-enrichr $ngenes_enrichr \
  --nterms-enrichr $nterms
