```{r eval=FALSE}

# conda activate cicero

library(Seurat)
library(tidyverse)
library(RColorBrewer)
library(MetBrewer)
library(viridis)
library(patchwork)
library(cowplot)
library(grid)
library(gridExtra)
library(ggrastr)
library(ggrepel)
library(hdWGCNA)
theme_set(theme_cowplot())

setwd("/dfs7/swaruplab/smorabit/collab/woodlab/cocaine_mouse_2021/Nurr2c_vs_GFP/")
fig_dir <- 'figures/for_paper/'
data_dir <-'/dfs7/swaruplab/smorabit/collab/woodlab/cocaine_mouse_2021/Nurr2c_vs_GFP/data/'

seurat_obj <- readRDS('/dfs7/swaruplab/smorabit/collab/woodlab/cocaine_mouse_2021/Nurr2c_vs_GFP/data/harmony_annotated_scWGCNA.rds')

# re-load color scheme:
load('/dfs7/swaruplab/smorabit/collab/woodlab/cocaine_mouse_2021/Nurr2c_vs_GFP/data/color_scheme.rda')


```


```{r eval=FALSE}

p <- PlotEmbedding(
  seurat_obj,
  group.by = 'annotation',
  label=FALSE,
  raster=TRUE,
  raster_dpi = 600,
  raster_scale=0.25,
  plot_theme = umap_theme() + NoLegend()
  color_df = color_df
) + ggtitle('')

pdf(paste0(fig_dir, 'habenula_umap.pdf'), width=5, height=5)
p
dev.off()


```


Set factor levels:

```{r eval=FALSE}


seurat_obj$annotation <- factor(
  as.character(seurat_obj$annotation),
  levels = c(
    'MHb-1', 'MHb-2', 'MHb-3', 'MHb-4', 'MHb-5',
    'LHb-1', 'LHb-2', 'LHb-3', 'LHb-4', 'LHb-5', 'LHb-6', 'LHb-7',
    'PHb-1', 'PHb-2', 'PHb-3', 'PHb-4', 'PHb-5', 'PHb-6',
    'OPC', 'ODC', 'MG', 'ASC', 'PER', 'END', 'EPD'
  )
)

seurat_obj$cell_type<- factor(
  as.character(seurat_obj$cell_type),
  levels = c(
    'MHb-Neuron', 'LHb-Neuron', 'PHb-Neuron',
    'OPC', 'ODC', 'MG', 'ASC', 'PER', 'END', 'EPD'
  )
)

seurat_obj$Sample<- factor(
  as.character(seurat_obj$Sample),
  levels = c(
    'Sample-1', 'Sample-2', 'Sample-3',
    'Sample-4', 'Sample-5', 'Sample-8',
    'Sample-11', 'Sample-14', 'Sample-16',
    'Sample-9', 'Sample-13'
  )
)

```


Cluster proportion bar plots

* Sample
* Condition

```{r eval=FALSE}


################################################################################
# snRNA-seq Proportion of Condition
################################################################################

seurat_meta <- seurat_obj@meta.data
batches <- seurat_meta$Sample %>% unique %>% as.character
cur_clusters  <- seurat_meta$annotation %>% unique %>% as.character

scale_vec <- table(seurat_meta$Sample)

proportion_df <- data.frame()
for(i in 1:length(cur_clusters)){
  cluster_meta <- subset(seurat_meta, annotation == cur_clusters[i])
  cur_df <- as.data.frame(table(cluster_meta$Sample)) %>% dplyr::rename(Count = Freq)

  # compute the non-normalized % of cells in each group
  cur_df$Freq <- cur_df$Count / sum(cur_df$Count)

  # scale frequency to the total number of clusters in each sample
  cur_df$Scaled <- cur_df$Count / scale_vec
  cur_df$Scaled <- cur_df$Scaled / sum(cur_df$Scaled)

  # add to ongoing proportion df
  cur_df$cluster <- cur_clusters[i]
  proportion_df <- rbind(proportion_df, cur_df)
}

proportion_df <- dplyr::rename(proportion_df, Sample = Var1)
proportion_df$cluster <- factor(proportion_df$cluster, levels=levels(seurat_meta$annotation))

p <- ggplot(proportion_df, aes(y=Scaled, x=cluster, fill=Sample)) +
  geom_bar(stat='identity') +
  geom_hline(yintercept = 0.5, linetype='dashed') +
  scale_y_continuous(expand = c(0,0)) +
  #scale_fill_manual(values=c('gray65', 'gray45')) +
  theme(
    panel.grid.major=element_blank(),
    panel.grid.minor=element_blank(),
    axis.text.x = element_text(angle=45, hjust=1),
    axis.title.x = element_blank(),
    legend.title = element_blank(),
    axis.line.y = element_line(colour = "black"),
    axis.line.x = element_blank()
  )

pdf(paste0(fig_dir, 'cluster_proportion_sample_scaled.pdf'), height=4, width=10)
print(p)
dev.off()

p <- ggplot(proportion_df, aes(y=Freq, x=cluster, fill=Sample)) +
  geom_bar(stat='identity') +
  geom_hline(yintercept = 0.5, linetype='dashed') +
  scale_y_continuous(expand = c(0,0)) +
  #scale_fill_manual(values=c('gray65', 'gray45')) +
  theme(
    panel.grid.major=element_blank(),
    panel.grid.minor=element_blank(),
    axis.text.x = element_text(angle=45, hjust=1),
    axis.title.x = element_blank(),
    legend.title = element_blank(),
    axis.line.y = element_line(colour = "black"),
    axis.line.x = element_blank()
  )

pdf(paste0(fig_dir, 'cluster_proportion_sample_raw.pdf'), height=4, width=10)
print(p)
dev.off()


################################################################################
# snRNA-seq Proportion of Condition
################################################################################

seurat_meta <- seurat_obj@meta.data
batches <- seurat_meta$Group %>% unique %>% as.character
cur_clusters  <- seurat_meta$annotation %>% unique %>% as.character

scale_vec <- table(seurat_meta$Group)

proportion_df <- data.frame()
for(i in 1:length(cur_clusters)){
  cluster_meta <- subset(seurat_meta, annotation == cur_clusters[i])
  cur_df <- as.data.frame(table(cluster_meta$Group)) %>% dplyr::rename(Count = Freq)

  # compute the non-normalized % of cells in each group
  cur_df$Freq <- cur_df$Count / sum(cur_df$Count)

  # scale frequency to the total number of clusters in each sample
  cur_df$Scaled <- cur_df$Count / scale_vec
  cur_df$Scaled <- cur_df$Scaled / sum(cur_df$Scaled)

  # add to ongoing proportion df
  cur_df$cluster <- cur_clusters[i]
  proportion_df <- rbind(proportion_df, cur_df)
}

proportion_df <- dplyr::rename(proportion_df, Group = Var1)
proportion_df$cluster <- factor(proportion_df$cluster, levels=levels(seurat_meta$annotation))

p <- ggplot(proportion_df, aes(y=Scaled, x=cluster, fill=Group)) +
  geom_bar(stat='identity') +
  geom_hline(yintercept = 0.5, linetype='dashed') +
  scale_y_continuous(expand = c(0,0)) +
  scale_fill_manual(values=c('gray65', 'gray45')) +
  theme(
    panel.grid.major=element_blank(),
    panel.grid.minor=element_blank(),
    axis.text.x = element_text(angle=45, hjust=1),
    axis.title.x = element_blank(),
    legend.title = element_blank(),
    axis.line.y = element_line(colour = "black"),
    axis.line.x = element_blank()
  )

pdf(paste0(fig_dir, 'cluster_proportion_condition_scaled.pdf'), height=4, width=10)
print(p)
dev.off()


################################################################################
# celltype snRNA-seq Proportion of Condition
################################################################################

seurat_meta <- seurat_obj@meta.data
batches <- seurat_meta$Group %>% unique %>% as.character
cur_clusters  <- seurat_meta$cell_type %>% unique %>% as.character

scale_vec <- table(seurat_meta$Group)

proportion_df <- data.frame()
for(i in 1:length(cur_clusters)){
  cluster_meta <- subset(seurat_meta, cell_type == cur_clusters[i])
  cur_df <- as.data.frame(table(cluster_meta$Group)) %>% dplyr::rename(Count = Freq)

  # compute the non-normalized % of cells in each group
  cur_df$Freq <- cur_df$Count / sum(cur_df$Count)

  # scale frequency to the total number of clusters in each sample
  cur_df$Scaled <- cur_df$Count / scale_vec
  cur_df$Scaled <- cur_df$Scaled / sum(cur_df$Scaled)

  # add to ongoing proportion df
  cur_df$cluster <- cur_clusters[i]
  proportion_df <- rbind(proportion_df, cur_df)
}

proportion_df <- dplyr::rename(proportion_df, Group = Var1)
proportion_df$cluster <- factor(proportion_df$cluster, levels=levels(seurat_meta$cell_type))

p <- ggplot(proportion_df, aes(y=Scaled, x=cluster, fill=Group)) +
  geom_bar(stat='identity') +
  geom_hline(yintercept = 0.5, linetype='dashed') +
  scale_y_continuous(expand = c(0,0)) +
  scale_fill_manual(values=group_colors) +
  theme(
    panel.grid.major=element_blank(),
    panel.grid.minor=element_blank(),
    axis.text.x = element_text(angle=45, hjust=1),
    axis.title.x = element_blank(),
    legend.title = element_blank(),
    axis.line.y = element_line(colour = "black"),
    axis.line.x = element_blank()
  )

pdf(paste0(fig_dir, 'celltype_proportion_condition_scaled.pdf'), height=4, width=10)
print(p)
dev.off()


##############################################################################
# proportion of cluster in each sample
##############################################################################

seurat_meta <- seurat_obj@meta.data
batches <- seurat_meta$annotation %>% unique %>% as.character
cur_clusters  <- seurat_meta$Sample %>% unique %>% as.character

proportion_df <- data.frame()
for(i in 1:length(cur_clusters)){
  cluster_meta <- subset(seurat_meta, Sample == cur_clusters[i])
  cur_df <- as.data.frame(table(cluster_meta$annotation)) %>% dplyr::rename(Count = Freq)

  # compute the non-normalized % of cells in each group
  cur_df$Freq <- cur_df$Count / sum(cur_df$Count)

  # add to ongoing proportion df
  cur_df$cluster <- cur_clusters[i]
  proportion_df <- rbind(proportion_df, cur_df)
}

proportion_df <- dplyr::rename(proportion_df, Group = Var1)
proportion_df$cluster <- factor(proportion_df$cluster, levels=levels(seurat_meta$Sample))

p <- ggplot(proportion_df, aes(y=Freq, x=cluster, fill=Group)) +
  geom_bar(stat='identity') +
  scale_y_continuous(expand = c(0,0)) +
  scale_fill_manual(values=cluster_colors) +
  theme(
    panel.grid.major=element_blank(),
    panel.grid.minor=element_blank(),
    axis.text.x = element_text(angle=45, hjust=1),
    axis.title.x = element_blank(),
    legend.title = element_blank(),
    axis.line.y = element_line(colour = "black"),
    axis.line.x = element_blank()
  )

pdf(paste0(fig_dir, 'sample_proportion_clusters.pdf'), height=4, width=10)
print(p)
dev.off()


##############################################################################
# proportion of celltype in each sample
##############################################################################

seurat_meta <- seurat_obj@meta.data
batches <- seurat_meta$cell_type %>% unique %>% as.character
cur_clusters  <- seurat_meta$Sample %>% unique %>% as.character


proportion_df <- data.frame()
for(i in 1:length(cur_clusters)){
  cluster_meta <- subset(seurat_meta, Sample == cur_clusters[i])
  cur_df <- as.data.frame(table(cluster_meta$cell_type)) %>% dplyr::rename(Count = Freq)

  # compute the non-normalized % of cells in each group
  cur_df$Freq <- cur_df$Count / sum(cur_df$Count)

  # add to ongoing proportion df
  cur_df$cluster <- cur_clusters[i]
  proportion_df <- rbind(proportion_df, cur_df)
}

proportion_df <- dplyr::rename(proportion_df, Group = Var1)
proportion_df$cluster <- factor(proportion_df$cluster, levels=levels(seurat_meta$Sample))

p <- ggplot(proportion_df, aes(y=Freq, x=cluster, fill=Group)) +
  geom_bar(stat='identity') +
  scale_y_continuous(expand = c(0,0)) +
  scale_fill_manual(values=celltype_colors) +
  theme(
    panel.grid.major=element_blank(),
    panel.grid.minor=element_blank(),
    axis.text.x = element_text(angle=45, hjust=1),
    axis.title.x = element_blank(),
    legend.title = element_blank(),
    axis.line.y = element_line(colour = "black"),
    axis.line.x = element_blank()
  )

pdf(paste0(fig_dir, 'sample_proportion_celltypes.pdf'), height=4, width=10)
print(p)
dev.off()


```

QC Violin plots

```{r eval=FALSE}


################################################################################
# Cluster level violin plots:
################################################################################

Idents(seurat_obj) <- seurat_obj$annotation
p <- VlnPlot(seurat_obj, features = 'total_counts', pt.size=0) +
  geom_boxplot(outlier.shape=NA, width=.25, fill='white') +
  scale_fill_manual(values=cluster_colors) +
  scale_y_continuous(labels=scales::comma) +
  ylab(expression(italic(N)[UMI])) +
  xlab('') + NoLegend() + ggtitle('')

pdf(paste0(fig_dir, 'vln_nUMI_clusters.pdf'), height=4, width=10)
p
dev.off()


p <- VlnPlot(seurat_obj, features = 'pct_counts_mt', pt.size=0) +
  geom_boxplot(outlier.shape=NA, width=.25, fill='white') +
  scale_fill_manual(values=cluster_colors) +
  scale_y_continuous(labels=scales::comma) +
  ylab("pct_counts_mt") +
  xlab('') + NoLegend() + ggtitle('')

pdf(paste0(fig_dir, 'vln_mito_clusters.pdf'), height=4, width=10)
p
dev.off()

p <- VlnPlot(seurat_obj, features = 'n_genes_by_counts', pt.size=0) +
  geom_boxplot(outlier.shape=NA, width=.25, fill='white') +
  scale_fill_manual(values=cluster_colors) +
  scale_y_continuous(labels=scales::comma) +
  ylab(expression(italic(N)[Genes])) +
  xlab('') + NoLegend() + ggtitle('')

pdf(paste0(fig_dir, 'vln_nGenes_clusters.pdf'), height=4, width=10)
p
dev.off()


################################################################################
# Sample level violin plots:
################################################################################

Idents(seurat_obj) <- seurat_obj$Sample
p <- VlnPlot(seurat_obj, features = 'total_counts', pt.size=0) +
  geom_boxplot(outlier.shape=NA, width=.25, fill='white') +
  scale_y_continuous(labels=scales::comma) +
  ylab(expression(italic(N)[UMI])) +
  xlab('') + NoLegend() + ggtitle('')

pdf(paste0(fig_dir, 'vln_nUMI_samples.pdf'), height=4, width=10)
p
dev.off()


p <- VlnPlot(seurat_obj, features = 'pct_counts_mt', pt.size=0) +
  geom_boxplot(outlier.shape=NA, width=.25, fill='white') +
  scale_y_continuous(labels=scales::comma) +
  ylab("pct_counts_mt") +
  xlab('') + NoLegend() + ggtitle('')

pdf(paste0(fig_dir, 'vln_mito_samples.pdf'), height=4, width=10)
p
dev.off()

p <- VlnPlot(seurat_obj, features = 'n_genes_by_counts', pt.size=0) +
  geom_boxplot(outlier.shape=NA, width=.25, fill='white') +
  scale_y_continuous(labels=scales::comma) +
  ylab(expression(italic(N)[Genes])) +
  xlab('') + NoLegend() + ggtitle('')

pdf(paste0(fig_dir, 'vln_nGenes_samples.pdf'), height=4, width=10)
p
dev.off()

```


Vln plot of Nr4a1,2,3

```{r eval=FALSE}

library(ggpubr)

cur_genes <- c('Nr4a1', 'Nr4a2', 'Nr4a3', 'Chat')

# plot in clusters
Idents(seurat_obj) <- seurat_obj$annotation
plots <- VlnPlot(
  seurat_obj, split.by='Group', features=cur_genes,
  pt.size = 0, combine=FALSE
)
for(i in 1:length(plots)){
  plots[[i]] <- plots[[i]] +
    stat_compare_means(aes(label = ..p.signif..), method='wilcox.test') +
    ylab('') + xlab('') +
    scale_fill_manual(values=group_colors) +
    coord_cartesian(ylim = c(0, 5))
}
pdf(paste0(fig_dir, 'Nr4a2_vln_clusters.pdf'), width=10, height=4)
for(p in plots){print(p)}
dev.off()


# plot in celltypes
Idents(seurat_obj) <- seurat_obj$cell_type
plots <- VlnPlot(
  seurat_obj, split.by='Group', features=cur_genes,
  pt.size = 0, combine=FALSE
)
for(i in 1:length(plots)){
  plots[[i]] <- plots[[i]] +
    stat_compare_means(aes(label = ..p.signif..), method='wilcox.test') +
    ylab('') + xlab('') +
    scale_fill_manual(values=group_colors) +
    coord_cartesian(ylim = c(0, 5))
}
pdf(paste0(fig_dir, 'Nr4a2_vln_celltype.pdf'), width=7, height=4)
for(p in plots){print(p)}
dev.off()


```



MELD Nurr2c perturbation score

```{r eval=FALSE}

# add MELD score to the seurat obj
meld_scores <- read.csv(paste0(data_dir, 'MELD_Nurr2c_likelihood.csv'))
seurat_obj@meta.data['Nurr2c_likelihood'] <- meld_scores$Nurr2c_likelihood


################################################################################
# MELD Score vlnplot sorted by median value
################################################################################

plot_df <- seurat_obj@meta.data %>% select(c(annotation, Nurr2c_likelihood, Group, cell_type))

color2 <- 'darkgoldenrod3'; color1 <- 'hotpink3'

# order groups by Neuronal vs non-neuronal, and by desceinding likelihood:
neuron_order <- plot_df %>% subset(cell_type %in% c('MHb-Neuron', 'LHb-Neuron', 'PHb-Neuron')) %>%
  mutate(annotation = droplevels(annotation)) %>%
  mutate(annotation = forcats::fct_reorder(annotation, Nurr2c_likelihood, .desc=TRUE)) %>%
  .$annotation %>% levels

nonneuron_order <- plot_df %>% subset(!(cell_type %in% c('MHb-Neuron', 'LHb-Neuron', 'PHb-Neuron'))) %>%
  mutate(annotation = droplevels(annotation)) %>%
  mutate(annotation = forcats::fct_reorder(annotation, Nurr2c_likelihood, .desc=TRUE)) %>%
  .$annotation %>% levels



plot_df$annotation <- factor(as.character(plot_df$annotation), levels=c(neuron_order, nonneuron_order))

p <- ggplot(plot_df, aes(x = annotation, y = Nurr2c_likelihood)) +
  ggrastr::rasterise(
    geom_jitter(
      shape=16, position=position_jitter(0.2), aes(color=Nurr2c_likelihood), alpha=0.8), dpi=800, scale=0.3) +
  scale_color_gradient2(low=color1, mid='lightgrey', high=color2, midpoint=0.5) +
  geom_boxplot(outlier.colour="black", outlier.shape=NA, notch=TRUE, fill='grey', alpha=0.25) +
  geom_hline(yintercept = 0.5, linetype='dashed', color='darkgrey') +
  RotatedAxis() + xlab('') + ylab('MELD Nurr2c Likelihood') +
  theme(
    axis.line.x = element_blank(),
    axis.line.y = element_blank(),
    panel.border = element_rect(size=1, fill=NA, color='black'),
    #axis.text.x = element_blank(),
    #axis.ticks=element_blank(),

  #  panel.grid.major.y = element_line(size=0.5,color='grey')
) +scale_y_continuous(expand = c(0, 0), limits = c(0, NA))



pdf(paste0(fig_dir, 'Nurr2c_likelihood_boxplot2.pdf'), width=8, height=2.5)
#p  colorbar + plot_layout(heights=c(10,1)) +
p
dev.off()


color_df$group <- factor(
  as.character(color_df$group),
  levels = levels(seurat_obj$annotation)
)

color_df$var <- 1
colorbar <- color_df %>%
  ggplot(aes(x=group, y=var, fill=group)) +
  geom_tile() +
  scale_fill_manual(values=color_df$colour) +
  NoLegend() +
  theme(
    plot.title=element_blank(),
    axis.line=element_blank(),
    axis.ticks.y=element_blank(),
    axis.text.y = element_blank(),
    #axis.text.y = element_blank(),
    axis.title = element_blank()

  ) + RotatedAxis()

  pdf(paste0(fig_dir, 'cbar.pdf'), width=8, height=1.5)
  #p  colorbar + plot_layout(heights=c(10,1)) +
  colorbar
  dev.off()




```


Plot UMAP with new plotting script:

```{r eval=FALSE}


color_df <- data.frame(
  group = names(cluster_colors),
  colour = as.character(cluster_colors)
)


p <- PlotEmbedding(
  seurat_obj,
  group.by = 'annotation',
  label=FALSE,
  raster=TRUE,
  raster_dpi = 800,
  raster_scale=0.25,
  plot_theme = umap_theme(),
  color_df = color_df
) + ggtitle('')

pdf(paste0(fig_dir, 'habenula_umap.pdf'), width=7, height=5)
p
dev.off()


p <- PlotEmbedding(
  seurat_obj,
  group.by = 'annotation',
  label=FALSE,
  raster=TRUE,
  raster_dpi = 800,
  raster_scale=0.25,
  plot_theme = umap_theme(),
  color_df = color_df
) + ggtitle('')

pdf(paste0(fig_dir, 'habenula_umap_labeled.pdf'), width=7, height=5)
p
dev.off()


```

Volcano

```{r eval=FALSE}

# Nr4a2 targets:
target_genes <- GetMotifTargets(seurat_obj)

# cluster DEGs
degs <- read.csv(file='/dfs7/swaruplab/smorabit/collab/woodlab/cocaine_mouse_2021/Nurr2c_vs_GFP/DEGs/data/cluster_Nurr2c_vs_GFP.csv')
degs$group <- factor(
  degs$group,
  levels = levels(seurat_obj$annotation)
)
name <- 'cluster'

# load degs:
degs <- read.csv(file='/dfs7/swaruplab/smorabit/collab/woodlab/cocaine_mouse_2021/Nurr2c_vs_GFP/DEGs/data/celltype_Nurr2c_vs_GFP.csv')
degs$group <- factor(
  degs$group,
  levels = levels(seurat_obj$cell_type)
)
name <- 'celltype'

# add Nr4a2 targets
target_genes <- GetMotifTargets(seurat_obj)
nr4a2_targets <- target_genes$NR4A2
degs$Nr4a2 <- degs$gene %in% nr4a2_targets

degs <- degs[!grepl("^mt-", degs$gene),]


min_val <- subset(degs, p_val_adj != 0) %>% .$p_val_adj %>% min
degs$p_val_adj <- ifelse(degs$p_val_adj ==0, min_val, degs$p_val_adj )

nlabel <- 5
color1 <- 'darkgoldenrod3'; color2 <- 'hotpink3'
Nr4a2 <- TRUE

label_genes <-c('Nr4a2')

# label the top and bottom significant genes by log fold change
cur_degs <- Reduce(rbind, lapply(unique(degs$group), function(x){
  cur <- subset(degs, group == x)

  if(Nr4a2){
    cur <- subset(cur, Nr4a2)
  } else{
    cur <- subset(cur, !Nr4a2)
  }

  top_thresh <- cur %>% subset(p_val_adj <= 0.05) %>% top_n(nlabel, wt=avg_log2FC) %>% .$avg_log2FC %>% min
  bottom_thresh <- cur %>% subset(p_val_adj <= 0.05) %>% top_n(-1*nlabel, wt=avg_log2FC) %>% .$avg_log2FC %>% max

  cur$anno <- ifelse(cur$p_val_adj <= 0.05 & cur$avg_log2FC >= top_thresh, cur$gene, NA)
  #cur$anno <- ifelse(cur$gene %in% label_genes | cur$anno != NA, cur$gene, NA)
  cur$anno <- ifelse(cur$p_val_adj <= 0.05 & cur$avg_log2FC <= bottom_thresh, cur$gene, cur$anno)
  cur$color <- ifelse(cur$p_val_adj > 0.05, 'gray', ifelse(cur$avg_log2FC > 0, color1, color2))
  cur
}))

groups <- unique(degs$group)
plot_list <- list()
for(cluster  in groups){


  print(cluster)
  plot_degs <- cur_degs %>% subset(group == cluster)

  p <- plot_degs %>% subset(Nr4a2) %>%
     ggplot(aes(x=avg_log2FC, y=-log10(p_val_adj))) +
     geom_hline(yintercept=-log10(0.05), linetype='dashed', color='grey')

  # plot genes that aren't Nr4a2 targets
  p <- p + ggrastr::rasterise(geom_point(
    data = plot_degs %>% subset(Nr4a2),
    aes(x=avg_log2FC, y=-log10(p_val_adj)),
    alpha=0.5, color='grey',
    inherit.aes = FALSE
  ), dpi=500)

  # plot genes that are Nr4a2 targets
  p <- p + ggrastr::rasterise(geom_point(
    alpha=0.5,
    color=plot_degs %>% subset(Nr4a2) %>% .$color
  ), dpi=500)

  p <- p +
     geom_point(
       inherit.aes=FALSE,
       data=subset(plot_degs, !is.na(anno)),
       aes(avg_log2FC, -log10(p_val_adj)),
       fill=subset(plot_degs, !is.na(anno)) %>% .$color,
       shape=21, size=3, color='black'
     ) +
     geom_text_repel(aes(label=anno), color='black', fontface='italic',  min.segment.length=0, max.overlaps=Inf) +
     xlim(-1*max(abs(plot_degs$avg_log2FC))-0.1, max(abs(plot_degs$avg_log2FC))+0.1) +
     ggtitle(paste0(cluster)) +
     theme(
       panel.grid.major = element_blank(),
       plot.title = element_text(hjust = 0.5, vjust=-0.25),
       legend.position='bottom',
       plot.margin = margin(c(0,0,0,0)),
       axis.title.y = element_blank(),
       axis.title.x = element_blank(),
       panel.border = element_rect(size=1, color='black', fill=NA),
       axis.line.y = element_blank(),
       axis.line.x = element_blank()
     )

    plot_list[[cluster]] <- p

}

pdf(paste0(fig_dir, 'MAST_celltype_volcano_Nr4a2.pdf'), width=7, height=2.75, useDingbats=FALSE)
wrap_plots(list(
  plot_list[['MHb-Neuron']], plot_list[['LHb-Neuron']], plot_list[['PHb-Neuron']]
), ncol=3)
dev.off()

pdf(paste0(fig_dir, 'MAST_cluster_volcano_other.pdf'), width=15, height=10, useDingbats=FALSE)
wrap_plots(plot_list, ncol=7)
dev.off()

```


Feature Plots for known marker genes

```{r eval=FALSE}

#############################################################
# Feature plot for Nr4a2 expression split by condition
#############################################################

p1 <- FeatureEmbedding(
  seurat_obj %>% subset(Group == 'Nurr2c'),
  'Nr4a2',
  same_range=FALSE,
  plot_max=4,
  plot_min=0,
  dpi=500,
  point_size=0.25,
  dpi_scale=0.5,
  order_points='shuffle'
)

p2 <- FeatureEmbedding(
  seurat_obj %>% subset(Group == 'GFP'),
  'Nr4a2',
  same_range=FALSE,
  plot_max=4,
  plot_min=0,
  dpi=500,
  point_size=0.25,
  dpi_scale=0.5,
  order_points='shuffle'
)

pdf(paste0(fig_dir, 'Nr4a2_featureplot.pdf'), width=4, height=8)
p1 / p2
dev.off()


#############################################################
# Feature plot for cell type markers
#############################################################

features=c(
  'Tac2', 'Chat',  # Mhb
  'Gap43', 'Chrm3',  # LHb,
  "Synpo2", "Grm1",  # Phb
  'Mog', 'Slc4a4', 'Csf1r', 'Pdgfra', 'Pdgfrb', 'Flt1', 'Foxj1' #non-neuronal
)

p <- FeatureEmbedding(
  seurat_obj,
  features=features,
  same_range=FALSE,
  ncol=5,
  plot_min=0,
  dpi=500,
  point_size=0.25,
  dpi_scale=0.5,
  order_points='shuffle'
)


pdf(paste0(fig_dir, 'markers_selected_featureplot.pdf'), width=20, height=10)
p
dev.off()




features=c(
  'Tac2', 'Chat', 'Syt9', 'Kcnip1',  # Mhb
  'Gap43', 'Chrm2', 'Chrm3', 'Hrt2c', 'Fam135b',  # LHb,
  'Rbfox1', 'Cit', "Synpo2", "Grm1",  # Phb
  'Pdgfra', 'Sox2ot', 'Plp1', 'Mog', 'Csf1r', 'Cx3cr1', 'Slc4a4', 'Slc39a12', 'Pdgfrb', 'Vtn', 'Flt1', 'Mecom',  'Foxj1' #non-neuronal
)

degs %>% subset(group == 'LHb-3') %>% top_n(15, wt=avg_log2FC)


Idents(seurat_obj) <- forcats::fct_rev(seurat_obj$annotation)
p <- DotPlot(seurat_obj, features=features, dot.min=0.25 ) +
  RotatedAxis() +
    scale_color_gradientn(
    colors=rev(inferno(256)),
    guide = guide_colorbar(barwidth=0.5, barheight=20, ticks=FALSE, label=FALSE)
) +
  ylab('') + xlab('') +
  theme(
    panel.border = element_rect(color = 'black', fill=NA, size=1),
    axis.line.y = element_blank(),
    axis.line.x = element_blank()
  )

pdf(paste0(fig_dir, 'markers_selected_dotplot2.pdf'), width=8.25, height=6.25, useDingbats=FALSE)
p
dev.off()


# selected genes:

```




Plot Volcanos For cluster DEGs

```{r eval=FALSE}

# load DEG data:
degs <- read.csv("/Volumes/GoogleDrive/Shared drives/WoodLab_Nurr2c/Nurr2c_vs_GFP/DEGs/DEG_tables/cluster_Nurr2c_vs_GFP.csv")


nlabel <- 5
color1 <- 'darkgoldenrod3'; color2 <- 'hotpink3'
# Nr4a2 <- TRUE

label_genes <-c('Nr4a2')

# label the top and bottom significant genes by log fold change
cur_degs <- Reduce(rbind, lapply(unique(degs$group), function(x){
  cur <- subset(degs, group == x)

  # if(Nr4a2){
  #   cur <- subset(cur, Nr4a2)
  # }

  top_thresh <- cur %>% subset(p_val_adj <= 0.05) %>% top_n(nlabel, wt=avg_log2FC) %>% .$avg_log2FC %>% min
  bottom_thresh <- cur %>% subset(p_val_adj <= 0.05) %>% top_n(-1*nlabel, wt=avg_log2FC) %>% .$avg_log2FC %>% max

  cur$anno <- ifelse(cur$p_val_adj <= 0.05 & cur$avg_log2FC >= top_thresh, cur$gene, NA)
  cur$anno <- ifelse(cur$p_val_adj <= 0.05 & cur$avg_log2FC <= bottom_thresh, cur$gene, cur$anno)
  cur$color <- ifelse(cur$p_val_adj > 0.05, 'gray', ifelse(cur$avg_log2FC > 0, color1, color2))
  cur
}))

groups <- unique(degs$group)
plot_list <- list()
for(cluster  in groups){


  print(cluster)
  plot_degs <- cur_degs %>% subset(group == cluster)

  p <- plot_degs %>% subset(Nr4a2) %>%
     ggplot(aes(x=avg_log2FC, y=-log10(p_val_adj))) +
     geom_hline(yintercept=-log10(0.05), linetype='dashed')

  # plot genes that aren't Nr4a2 targets
  p <- p + ggrastr::rasterise(geom_point(
    data = plot_degs %>% subset(!Nr4a2),
    aes(x=avg_log2FC, y=-log10(p_val_adj)),
    alpha=0.5, color='grey',
    inherit.aes = FALSE
  ), dpi=500)

  # plot genes that are Nr4a2 targets
  p <- p + ggrastr::rasterise(geom_point(
    alpha=0.5,
    color=plot_degs %>% subset(Nr4a2) %>% .$color
  ), dpi=500)

  p <- p +
     geom_point(
       inherit.aes=FALSE,
       data=subset(plot_degs, !is.na(anno)),
       aes(avg_log2FC, -log10(p_val_adj)),
       fill=subset(plot_degs, !is.na(anno)) %>% .$color,
       shape=21, size=3, color='black'
     ) +
     geom_text_repel(aes(label=anno), color='black', fontface='italic',  min.segment.length=0) +
     xlim(-1*max(abs(plot_degs$avg_log2FC))-0.1, max(abs(plot_degs$avg_log2FC))+0.1) +
     ggtitle(paste0(cluster)) +
     theme(
       panel.grid.major = element_blank(),
       plot.title = element_text(hjust = 0.5),
       legend.position='bottom'
     )

    plot_list[[cluster]] <- p

}

pdf(paste0(fig_dir, 'MAST_cluster_volcano_Nr4a2.pdf'), width=20, height=20, useDingbats=FALSE)
wrap_plots(plot_list, ncol=5)
dev.off()



```


Compute MHb-specific Nr4a2 target gene score:

```{r eval=FALSE}


# load degs:
degs <- read.csv(file='/dfs7/swaruplab/smorabit/collab/woodlab/cocaine_mouse_2021/Nurr2c_vs_GFP/DEGs/data/cluster_marker_DEGs.csv')
degs$group <- factor(
  degs$group,
  levels = levels(seurat_obj$annotation)
)

# Nr4a2 targets:
target_genes <- GetMotifTargets(seurat_obj)
nr4a2_targets <- target_genes$NR4A2

# add Nr4a2 targets to the DEGs:
nr4a2_old <- degs$Nr4a2
degs$Nr4a2 <- degs$gene %in% nr4a2_targets

# MHb markers that are also nr4a2 targets
nr4a2_degs <- degs[grepl('MHb', degs$group),] %>% subset(avg_log2FC >= 1 & Nr4a2 & p_val_adj <= 0.05) %>% .$gene %>% unique
length(nr4a2_degs)

df <- data.frame(
  X = 1:length(nr4a2_degs),
  gene = nr4a2_degs
)

# compute the Nr4a2 MHb score
nr4a2_tf_score <-  Seurat::AddModuleScore(seurat_obj, features=list('Nr4a2' = nr4a2_degs))@meta.data
nr4a2_tf_score <- nr4a2_tf_score[,ncol(nr4a2_tf_score)]

# add score to seurat object
seurat_obj$Nr4a2_MHb_score <- nr4a2_tf_score

p <- FeatureEmbedding(
  seurat_obj,
  features='Nr4a2_MHb_score',
  plot_max=NULL,
  plot_min=0,
  dpi=500,
  point_size=0.25,
  dpi_scale=0.25,
  order_points='shuffle'
)


pdf(paste0(fig_dir, 'umap_nr4a2_score.pdf'), width=5, height=5)
p
dev.off()

```


Ex vivo activation signature

```{r eval=FALSE}

exam_genes <- read.csv('~/swaruplab/smorabit/collab/woodlab/cocaine_mouse_2021/Nurr2c_vs_GFP/data/exAMgenes_Marsh2022.csv')

genes_test <- exam_genes$ExAm_ALL
genes_test <- genes_test[genes_test != '']
genes_test <- genes_test[genes_test %in% rownames(seurat_obj)]

# compute the Nr4a2 MHb score
exam_score <-  Seurat::AddModuleScore(seurat_obj, features=list('exam' = genes_test))@meta.data
exam_score <- exam_score[,ncol(exam_score)]

# add score to seurat object
seurat_obj$exam_score <- exam_score

# compute the Nr4a2 MHb score
exam_score <- UCell::AddModuleScore_UCell(seurat_obj, features=list('exam' = genes_test))@meta.data
exam_score <- exam_score[,ncol(exam_score)]

# add score to seurat object
seurat_obj$exam_score_ucell <- exam_score



p <- FeatureEmbedding(
  seurat_obj,
  features=c('exam_score', 'exam_score_ucell'),
  plot_max=NULL,
  plot_min=0,
  ncol=2,
  dpi=200,
  point_size=0.25,
  dpi_scale=0.25,
  order_points='shuffle'
)


pdf(paste0(fig_dir, 'umap_exam_score.pdf'), width=5, height=5)
p
dev.off()


# plot doublet score
p <- FeatureEmbedding(
  seurat_obj,
  features=c('doublet_scores'),
  plot_max=1,
  plot_min=0.05,
  ncol=2,
  dpi=500,
  point_size=0.25,
  dpi_scale=0.25,
  order_points='shuffle'
)

pdf(paste0(fig_dir, 'umap_doublet_score.pdf'), width=5, height=5)
p
dev.off()


```
