
Integrating our dataset with Hashikawa et al Habenula dataset 
(Figure S3)

```{r eval=FALSE}

# conda activate cicero

library(Seurat)
library(tidyverse)
library(RColorBrewer)
library(MetBrewer)
library(viridis)
library(patchwork)
library(cowplot)
library(grid)
library(gridExtra)
theme_set(theme_cowplot())

setwd("/dfs7/swaruplab/smorabit/collab/woodlab/cocaine_mouse_2021/Nurr2c_vs_GFP/revision/integration/")
fig_dir <- 'figures/'
data_dir <- 'data/'


# load seurat obj
seurat_obj <- readRDS(file='/dfs7/swaruplab/smorabit/collab/woodlab/cocaine_mouse_2021/Nurr2c_vs_GFP/revision/data/harmony_annotated_integration.rds')

# load hashikawa dataset:
seurat_hashikawa <- readRDS('/dfs7/swaruplab/smorabit/collab/woodlab/cocaine_mouse_2021/analysis/test_harmony/data/hashikawa_seurat.rds')

# re-load integrated data:
#seurat_joint <- readRDS('/dfs7/swaruplab/smorabit/collab/woodlab/cocaine_mouse_2021/Nurr2c_vs_GFP/integration/data/Nurr2c_hashikawa_integrated_seurat.rds')

# re-load color scheme:
load('/dfs7/swaruplab/smorabit/collab/woodlab/cocaine_mouse_2021/Nurr2c_vs_GFP/revision/data/color_scheme.rda')

```


Set factor levels for clusters
```{r eval=FALSE}


seurat_hashikawa$celltype_neuron <- factor(
  as.character(seurat_hashikawa$celltype_neuron),
  levels = c(
    'MHb1', 'MHb2', 'MHb3', 'MHb4', 'MHb5', 'MHb6',
    'LHb1', 'LHb2', 'LHb3', 'LHb4', 'LHb5', 'LHb6',
    'PHb Neuron',
    'OPC1', 'OPC2', 'OPC3', 'Oligo1', 'Oligo2', 'Oligo3',
    'Microglia', 'Astrocyte1', 'Astrocyte2', 'Mural', 'Endothelial', 'Epen'
  )
)


```



Joint Analysis of Hashikawa data with our data using LIGER:

```{r eval=FALSE}

library(rliger)

expr_matrix <- GetAssayData(seurat_obj, slot='counts')
h_expr_matrix <- GetAssayData(seurat_hashikawa, slot='counts')

genes_keep <- intersect(rownames(expr_matrix), rownames(h_expr_matrix))

expression_list <- list(
  'Nurr2c' = expr_matrix[genes_keep,],
  'Hashikawa' = h_expr_matrix[genes_keep,]
)

nurr2c_meta <- seurat_obj@meta.data %>%
  select(c(annotation)) %>%
  dplyr::rename(cluster = annotation)
nurr2c_meta$Dataset <- 'Nurr2c'

hash_meta <- seurat_hashikawa@meta.data %>%
  select(c(celltype_neuron)) %>%
  dplyr::rename(cluster = celltype_neuron)
hash_meta$Dataset <- "Hashikawa"

seurat_joint <- Seurat::CreateSeuratObject(
  cbind(expression_list$Nurr2c, expression_list$Hashikawa),
  meta.data = rbind(nurr2c_meta, hash_meta)
)

# create liger object:
liger_obj <- createLiger(expression_list)
liger_obj <- normalize(liger_obj)

pdf("figures/liger_variable_genes.pdf", width=8, height=8)
liger_obj <- selectGenes(
  liger_obj,
  var.thresh =c(0.25, 0.05),
  do.plot=T
)
dev.off()
liger_obj@var.genes %>% length
liger_obj <- scaleNotCenter(liger_obj)

# iNMF
liger_obj <- optimizeALS(liger_obj, k = 30)

# quantile normalization
liger_obj <- quantile_norm(liger_obj)

saveRDS(liger_obj, paste0(data_dir, 'UCI_hashikawa_integrated_liger.rds'))
liger_obj <- readRDS(paste0(data_dir, 'UCI_hashikawa_integrated_liger.rds'))

calcAlignment(liger_obj)
# [1] 0.9004578

# transfer iNMF matrix to seurat obj:
seurat_joint@reductions$iNMF <- CreateDimReducObject(
    loadings=t(liger_obj@W),
    embeddings=liger_obj@H.norm[colnames(seurat_joint),],
    key="iNMF_",
    assay="RNA"
  )
VariableFeatures(seurat_joint) <- liger_obj@var.genes


# UMAP
seurat_joint <- RunUMAP(seurat_joint, reduction='iNMF', dims=1:30, n.neighbors=5L, min.dist=0.1)

p1 <- DimPlot(seurat_joint, split.by='Dataset', group.by='cluster', label=TRUE) + hdWGCNA::umap_theme() + NoLegend() + theme(plot.title = element_text(hjust = 0.5))
pdf(paste0(fig_dir, 'umap_integrated_liger_ALS_original_cluster.pdf'), width=10, height=5)
p1
dev.off()

p1 <- DimPlot(seurat_joint, group.by='Dataset') +  hdWGCNA::umap_theme() + theme(plot.title = element_text(hjust = 0.5))
pdf(paste0(fig_dir, 'umap_integrated_liger.pdf'), width=7, height=7)
p1
dev.off()

# save integrated data:
saveRDS(seurat_joint, paste0(data_dir, 'Nurr2c_hashikawa_integrated_seurat.rds'))

```


Plot integrated UMAPs for the paper:

```{r eval=FALSE}

source('/dfs7/swaruplab/smorabit/analysis/scWGCNA/bin/spatial_functions.R')

library(MetBrewer)
cluster_colors_hashikawa = paste0(met.brewer("Morgenstern", length(unique(seurat_hashikawa$celltype_neuron))))
names(cluster_colors_hashikawa) <- levels(seurat_hashikawa$celltype_neuron)

cluster_colors <- c(cluster_colors, cluster_colors_hashikawa)

color_df <- data.frame(
  group = names(cluster_colors),
  colour = as.character(cluster_colors)
)

p <- PlotEmbedding(
  seurat_joint,
  group.by = 'cluster',
  split.by = 'Dataset',
  label=FALSE,
  raster=TRUE,
  raster_dpi = 600,
  point_size=0.5,
  raster_scale=0.5,
  plot_under=TRUE,
  plot_theme = hdWGCNA::umap_theme(),
  color_df = color_df
)

pdf(paste0(fig_dir, 'umap_integrated.pdf'), width=15, height=5)
wrap_plots(p, ncol=2)
dev.off()

color_df <- data.frame(
  group = names(cluster_colors_hashikawa),
  colour = as.character(cluster_colors_hashikawa)
)

p <- PlotEmbedding(
  seurat_hashikawa,
  group.by = 'celltype_neuron',
  #split.by = 'Dataset',
  label=TRUE,
  raster=TRUE,
  raster_dpi = 600,
  point_size=0.5,
  raster_scale=0.5,
  plot_theme = hdWGCNA::umap_theme(),
  color_df = color_df
)

pdf(paste0(fig_dir, 'umap_hashikawa.pdf'), width=7, height=7)
p
dev.off()


```

Plot marker genes in hashikawa dataset

```{r eval=FALSE}

# read combined
degs <- read.csv('/dfs7/swaruplab/smorabit/collab/woodlab/cocaine_mouse_2021/Nurr2c_vs_GFP/revision/DEGs/data/cluster_marker_DEGs.csv')
group_levels <- levels(seurat_obj$cell_identity)
degs$group <- factor(as.character(degs$group), levels=group_levels)


n_degs <- 5
plot_genes <- degs %>%
  arrange(group) %>%
  subset(p_val_adj <= 0.05) %>%
  group_by(group) %>%
  top_n(n_degs, wt=avg_log2FC)  %>%
  .$gene


# set random seed
set.seed(42)

seurat_hashikawa$barcode <- colnames(seurat_hashikawa)
#temp <- seurat_hashikawa@meta.data %>% group_by(celltype_neuron) %>% sample_n(100)



seurat_hashikawa$ordered_clusters <- factor(
  as.character(seurat_hashikawa$celltype_neuron),
  levels = c(
    'MHb1', 'MHb2', 'MHb3', 'MHb4', 'MHb5', 'MHb6',
    'LHb1', 'LHb2', 'LHb3', 'LHb4', 'LHb5', 'LHb6',
    'PHb Neuron',
    'OPC1', 'OPC2', 'OPC3',
    'Oligo1', 'Oligo2', 'Oligo3',
    'Microglia',
    'Astrocyte1', 'Astrocyte2',
    'Mural', 'Endothelial', 'Epen'
  )
)

seurat_hashikawa$ordered_clusters <- fct_rev(seurat_hashikawa$ordered_clusters)

seurat_hashikawa <- ScaleData(seurat_hashikawa, features = unlist(plot_genes))

p <- DoHeatmap(
  seurat_hashikawa,
  features=unlist(plot_genes),
  group.by='ordered_clusters',
  raster=TRUE, slot='scale.data',
  group.colors=cluster_colors_hashikawa
) + theme(axis.text.y = element_text(face='italic', size=9))

pdf(paste0(fig_dir, 'marker_gene_heatmap_hashikawa.pdf'), width=16, height=14, useDingbats=FALSE)
p
dev.off()


```



Plot integrated UMAPs for the paper:

```{r eval=FALSE}

# helper function to shuffle points when plotting:
shuffle_points <- function(df){
  return(df[sample(1:dim(df)[1], dim(df)[1]),])
}

seurat_joint@meta.data$UMAP_1 <- seurat_joint@reductions$umap@cell.embeddings[,1]
seurat_joint@meta.data$UMAP_2 <- seurat_joint@reductions$umap@cell.embeddings[,2]
seurat_hashikawa@meta.data$UMAP_1 <- seurat_hashikawa@reductions$umap@cell.embeddings[,1]
seurat_hashikawa@meta.data$UMAP_2 <- seurat_hashikawa@reductions$umap@cell.embeddings[,2]


################################################################################
# UMAP split by Dataset colored by cluster
################################################################################

library(ggrastr)

sample_colors = paste0(met.brewer("Renoir", 16))
names(sample_colors) <- levels(seurat_rna$Sample.ID)


# Nurr2c Dataset
plot_df <- seurat_joint@meta.data %>% subset(Dataset == "Nurr2c" ) %>% shuffle_points
plot_df$cluster <- factor(
  as.character(plot_df$cluster),
  levels = levels(seurat_obj$annotation)
)

cluster_colors = paste0(met.brewer("Renoir", length(levels(seurat_obj$annotation))))
names(cluster_colors) <- levels(seurat_obj$annotation)


p1 <- plot_df %>%
  ggplot(aes(x=UMAP_1, y=UMAP_2, color=cluster)) +
  scale_color_manual(values=cluster_colors) +
  rasterise(geom_point(
    data = seurat_joint@meta.data,
    aes(x=UMAP_1, y=UMAP_2), color='lightgray', size=0.1
  ), dpi=800) +
  rasterise(geom_point(size=0.25, alpha=0.75), dpi=800) +
  umap_theme + ggtitle('')


# Hashikawa Dataset
plot_df <- seurat_joint@meta.data %>% subset(Dataset == "Hashikawa" ) %>% shuffle_points
plot_df$cluster <- factor(
  as.character(plot_df$cluster),
  levels = levels(seurat_hashikawa$celltype_neuron)
)

cluster_colors = paste0(met.brewer("Morgenstern", length(levels(plot_df$cluster))))
names(cluster_colors) <- levels(plot_df$cluster)

p2 <- plot_df %>%
  ggplot(aes(x=UMAP_1, y=UMAP_2, color=cluster)) +
  scale_color_manual(values=cluster_colors) +
  rasterise(geom_point(
    data = seurat_joint@meta.data,
    aes(x=UMAP_1, y=UMAP_2), color='lightgray', size=0.1
  ), dpi=800) +
  rasterise(geom_point(size=0.25, alpha=0.75), dpi=800) +
  umap_theme + ggtitle('')




pdf(paste0(fig_dir, 'umap_integrated_clusters_split_dataset.pdf'), width=12, height=4, useDingbats=FALSE)
p1  + p2  + plot_layout(ncol=2)
dev.off()


# plot hashikawa et al umap:


# Hashikawa Dataset
plot_df <- seurat_hashikawa@meta.data %>% shuffle_points()
plot_df$cluster <- factor(
  as.character(plot_df$celltype_neuron),
  levels = levels(seurat_hashikawa$celltype_neuron)
)

cluster_colors = paste0(met.brewer("Morgenstern", length(levels(plot_df$cluster))))
names(cluster_colors) <- levels(plot_df$cluster)

p2 <- plot_df %>%
  ggplot(aes(x=UMAP_1, y=UMAP_2, color=cluster)) +
  scale_color_manual(values=cluster_colors) +
  rasterise(geom_point(
    data = seurat_joint@meta.data,
    aes(x=UMAP_1, y=UMAP_2), color='lightgray', size=0.1
  ), dpi=800) +
  geom_point(size=0.25, alpha=0.75) +
  umap_theme + ggtitle('')




pdf(paste0(fig_dir, 'umap_hashikawa.pdf'), width=7, height=6, useDingbats=FALSE)
p2
dev.off()


png(paste0(fig_dir, 'umap_integrated_clusters_split_dataset.png'), width=8, height=4, res=500, units='in')
p1 + NoLegend() +
p2 + NoLegend() +
plot_layout(ncol=2)
dev.off()

p2 <- DimPlot(
  seurat_hashikawa, group.by='celltype_neuron',
  label = FALSE) +
  #scale_color_manual(values=cluster_colors) +
  ggtitle('') +
  umap_theme()

leg <- cowplot::get_legend(p2)
pdf(paste0(fig_dir, 'umap_integrated_clusters_hashikawa_legend.pdf'), width=3, height=5, useDingbats=FALSE)
grid.draw(leg)
dev.off()

```

Joint iNMF dot plot:

```{r eval=FALSE}

colfunc <- colorRampPalette(c('white', brewer.pal(9, 'Purples' )[2:9]))


p <- DotPlot(
  #subset(seurat_joint, dataset=='Nurr2c'),
  seurat_joint,
  features = paste0('iNMF_', 1:30),
  group.by = 'cluster'
) + RotatedAxis() +
  scale_color_gradientn(colors=colfunc(256))

pdf(paste0(fig_dir, 'dotplot_iNMF.pdf'), width=12, height=8, useDingbats=FALSE)
p
dev.off()

```

