#!/bin/bash
#SBATCH --job-name=cocaine
#SBATCH -p standard
#SBATCH -A vswarup_lab
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --error=slurm-%J.err
#SBATCH --mem 128G
#SBATCH --array=0-10
#SBATCH --time=72:00:00

# to run this script:
# sbatch cellranger_count.sub

data_dir="/dfs3b/swaruplab/smorabit/collab/woodlab/cocaine_mouse_2021/data/fastqs/"

# get different sample names:
samples=($(ls $data_dir | cut -d '_' -f 1-3 | uniq))

# get current sample based on the SLURM job ID
let index="$SLURM_ARRAY_TASK_ID"
sample=${samples[$index]}
echo $sample

# set the reference transcriptome
transcriptome="/dfs3b/swaruplab/smorabit/resources/cellranger_reference/refdata-gex-mm10-2020-A/"

# run cellranger count for this sample
/dfs3b/swaruplab/smorabit/bin/software/cellranger/cellranger-6.0.0/cellranger count \
  --id=$sample \
  --transcriptome=$transcriptome \
  --fastqs=$data_dir \
  --sample=$sample \
  --localcores=32 \
  --localmem=128 \
  --expect-cells=10000 \
  --include-introns
