#!/bin/bash
#SBATCH --job-name=FindMarkers
#SBATCH -p standard
#SBATCH -A vswarup_lab
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --error=slurm-%J.err
#SBATCH --mem 48G
#SBATCH --array=1-21
#SBATCH --time=6:00:00

source ~/.bashrc
conda activate voyager

# seurat object path:
seurat="/dfs7/swaruplab/smorabit/collab/woodlab/cocaine_mouse_2021/Nurr2c_vs_GFP/revision/data/harmony_annotated_integration.rds"
outdir="/dfs7/swaruplab/smorabit/collab/woodlab/cocaine_mouse_2021/Nurr2c_vs_GFP/revision/DEGs/cluster_markers/"
type="markers"
name="cluster_markers"
cluster="cell_identity"
latent="total_counts,Assignment,Sample"

# launch R script:
Rscript --vanilla ~/swaruplab/smorabit/collab/woodlab/cocaine_mouse_2021/bin/parallel_DEGs.R \
    --seurat $seurat \
    --outdir $outdir \
    --type $type \
    --cluster $cluster \
    --name $name \
    --index $SLURM_ARRAY_TASK_ID \
    --test "MAST" \
    --pos "FALSE" \
    --pct 0.1 \
    --logfc 0.1 \
    --verbose "TRUE" \
    --latent $latent \
    --cores 16
